### ISSUE TITLE
add the ability to see version of ocm 

### ISSUE THREAD

**Issue by mgold1234** [open-cluster-management-io/clusteradm#205]
now we can see the version only if we go to deployment from hub cluster.
it will be usefull to see version outside.
maybe in clusteradm version :
client		version	:v0.1.1
server release	version	:v1.19.7
clusteradm version:

**Comment by jichenjc** [comment]
which version are we plan to show? the bundle version? e.g 0.7.0?

**Comment by yue9944882** [comment]
i think we need to clarify the relationship between the overall bundle version and per-component version, note that each component may have its independent patch release. e.g. we cant expect every component (work, registration) under 0.7.1 bundle version to be at 0.7.1. otherwise it's hard for clusteradm users to understand what does the returned bundle version actually mean from `clusteradm version`..

**Comment by jichenjc** [comment]
I propose to make the `default`  https://github.com/open-cluster-management-io/clusteradm/blob/main/pkg/helpers/version/version.go#L55 as a variable so that we can show this version in the output e.g 

clusteradm bundle default version: 0.7.0 

and 

clusteradm bundle supported version: 0.5, 0.6,0.7 

any comments?

**Comment by jichenjc** [comment]
https://github.com/open-cluster-management-io/clusteradm/pull/215

**Comment by ilan-pinto** [comment]
i think this issue be closed
